version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: chatgpt-proxy-web
    ports:
      - "7000:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80 